# Generated by Django 5.2.4 on 2025-07-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_registration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('meetup', 'Meetup'), ('seminar', 'Seminar'), ('networking', 'Networking'), ('social', 'Social'), ('sports', 'Sports & Fitness'), ('entertainment', 'Entertainment'), ('educational', 'Educational'), ('business', 'Business'), ('technology', 'Technology'), ('arts', 'Arts & Culture'), ('food', 'Food & Drink'), ('charity', 'Charity & Fundraising'), ('other', 'Other')], max_length=100),
        ),
    ]
