# Generated by Django 5.2.4 on 2025-07-21 18:37

from django.db import migrations
from django.contrib.auth.models import Group


def create_user_groups(apps, schema_editor):
    """Create default user groups."""
    Group.objects.get_or_create(name='Organizer')
    Group.objects.get_or_create(name='Attendee')


def remove_user_groups(apps, schema_editor):
    """Remove user groups."""
    Group.objects.filter(name__in=['Organizer', 'Attendee']).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user_groups, remove_user_groups),
    ]
